version: '3.8' # Defines the Docker Compose file structure version

services:
  postgres:
    image: postgres:16-alpine # Uses a lightweight, secure, and production-ready PostgreSQL version
    container_name: telecom_postgres # Gives a unique name to our database container for easy tracking
    ports:
      - "${DB_PORT}:5432" # Maps the database port from .env to the host machine so Spring & DBeaver can connect
    environment:
      POSTGRES_USER: ${DB_USER}         # Configures the master username using the secure .env variable
      POSTGRES_PASSWORD: ${DB_PASSWORD} # Configures the master password using the secure .env variable
      POSTGRES_DB: ${DB_NAME}           # Automatically creates our main database instance on startup
    env_file:
      - ../.env # Tells Docker that the .env file is located exactly one folder up (in the root directory)
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persists all database records on your PC so data is never lost

volumes:
  postgres_data: # Declares the named volume for data persistence

