const API_ENDPOINTS = {
  APP_USER: "/APP_USER",
  CUSTOMERS: "/CUSTOMERS",
  PRODUCT_CATALOG: "/PRODUCT_CATALOG",
  INVENTORY_STOCK: "/INVENTORY_STOCK",
  INVENTORY_ASSIGNMENT: "/INVENTORY_ASSIGNMENT",
  SALES_CHANNELS: "/SALES_CHANNELS",
};

export default API_ENDPOINTS;